name: Go Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21  # Replace with your desired Go version

    - name: Build Go program
      run: go build -o my-go-program
      working-directory: ./

    - name: Run Go program
      run: ./my-go-program
      working-directory: ./
